### ISSUE TITLE
update highlight js/ provide example with other highlighters

### ISSUE THREAD

**Issue by dit7ya** [novacbn/svelte-codejar#1]
Hey, thanks for this amazing project. 

The demo app uses 10.4.0 version of highlightjs which is currently deprecated. The latest version does not support the functions used in the example. Could you please update the examples for the latest version? 
Also it would be very nice to have more examples of highlighting (correct way to do it with SvelteKit) and with other libraries such as [Prism](https://prismjs.com/).

**Comment by novacbn** [comment]
I updated the [`README.md#syntax-highlighting`](https://github.com/novacbn/svelte-codejar/blob/master/README.md#syntax-highlighting) changing out the deprecated highlight.js stuff and added sample with PrismJS _(requires v0.0.3)_. And added [`README.md#sveltekit--referenceerror-window-is-not-defined`](https://github.com/novacbn/svelte-codejar/blob/master/README.md#sveltekit--referenceerror-window-is-not-defined) shows how to fix  SvelteKit SSR errors (had to deal with this myself recently).

I also migrated the [demo](https://novacbn.github.io/svelte-codejar/demo) to SvelteKit and added support for switching between PrismJS / highlight.js to it. Although it's a little complex using iframes for style isolation. 


https://user-images.githubusercontent.com/31122674/118285184-319b6780-b49f-11eb-934a-71fa86c06010.mp4

**Comment by dit7ya** [comment]
Oh this is super cool! Thank you so much.

**Comment by novacbn** [comment]
No problem.
