### ISSUE TITLE
Cannot bind to value in SvelteKit?

### ISSUE THREAD

**Issue by emptypockets-dev** [novacbn/svelte-codejar#3]
Is bind:value intended to be a 2-way binding? 

I was hoping to use the output in a form submission but I can't seem to get the value to update. 

I'm using the SvelteKit setup you have outlined. Is that a limitation?

**Comment by novacbn** [comment]
Sorry about that, I must have lost it in the transition to TypeScript. It's back now in `0.1.1`.

https://svelte.dev/repl/6f9178bf6bac4aaeaebdc14666354205?version=3.43.0

**Comment by novacbn** [comment]
Going to close the issue since there was no response. Reopen and let me know if your issue still isn't resolved.
