### ISSUE TITLE
Cursor position wrong after first input - highlight

### ISSUE THREAD

**Issue by michAtEl** [novacbn/svelte-codejar#5]
When I edit for the first time, the cursor jumps to the first position at the first line.

Steps to reproduce:
- open https://svelte.dev/repl/51f1433efcf84702b9501188ce3986b7?version=3.46.4
- position the cursor in the editor (not the first position of the first line)
- enter a char or press enter

I was not able to reproduce this issue with codjar (without svelte-codejar).
The Cursor behaves correctly without highlight.

Any Ideas?
Thanks
Michael

**Comment by michAtEl** [comment]
Here ist a workaround: set the initial value in onMount
https://svelte.dev/repl/92d2f9e7f24343be971d758f77370347?version=3.46.4

**Comment by novacbn** [comment]
Seemed to be a false positive with reactivity in the codebase. Fixed now with `0.1.2` and in your non-workaround REPL.

**Comment by michAtEl** [comment]
The bugfix works in my project.
Thanks!
Michael
